name: SoulcraftAuth
version: 1.1
main: de.dal3x.scAuth.main.SCAuth
author: DAL3X
api-version: 1.15
commands:
  discordtag:
    usage: /<command>
    description: Gibt den Discord Benutzernamen des Spielers
  verify:
    usage: /<command>
    description: Verifiziert einen Discord-Account auf den Spielernamen
    aliases: verifizieren
  unverify:
    usage: /<command>
    description: Hebt die Verifizierung eines Discord-Accounts auf
    aliases: entverifizieren